### ISSUE TITLE
[Bug]: removed comments result in ```TypeError: replyToken is required and must be of type "string"```

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/yt-comment-scraper#39]
https://youtu.be/KMtrY6lbjcY

https://user-images.githubusercontent.com/73130443/172027693-df496e89-cac6-4101-a1a4-cb380c05064a.mp4

https://youtu.be/wj3_9qG6Yv8 (enable invidious fallback)

https://user-images.githubusercontent.com/73130443/172027753-f009b240-198d-40d6-9bec-22a4aeed6f38.mp4

**Comment by ChunkyProgrammer** [comment]
Fixed in https://github.com/FreeTubeApp/FreeTube/pull/2460
