### ISSUE TITLE
bug at htmlParser.js, TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by gurumnyang** [FreeTubeApp/yt-comment-scraper#69]
```
 const contentText = comment.contentText.runs

      const customEmojis = []
      contentText.forEach((content) => {
        if (content.text === '\n') {
          text = text + '<br>'
        } else if (content.bold || content.strikethrough || content.italics) {
          let formattedText = content.text

          if (content.bold) {
            formattedText = '<b>' + formattedText + '</b>'
          }
          if (content.strikethrough) {
            formattedText = '<s>' + formattedText + '</s>'
          }
          if (content.italics) {
            formattedText = '<i>' + formattedText + '</i>'
          }

          text = text + formattedText
        } else {
          text = text + content.text
        }
        if (typeof content.emoji !== 'undefined') {
          customEmojis.push({
            text: content.text,
            emojiThumbnails: content.emoji.image.thumbnails
          })
        }
      })
```
![image](https://user-images.githubusercontent.com/62387796/200597098-57f47557-c0fc-452b-bda2-db2ed1980afd.png)

module cannot process emply content comment. Before proceeding `contentText.forEach((content) => {` , it must check is comment is empty

**Comment by ChunkyProgrammer** [comment]
Hi, what video is this comment on for testing purposes?

**Comment by gurumnyang** [comment]
https://www.youtube.com/watch?v=-hRdcwLzdts&lc=UgxAUxjBkENjo2IzsA54AaABAg

I checked the problem while crawling various video comments as a test.

The content element of this comment
```<yt-formatted-string id="content-text" slot="content" split-lines="" user-input="" class="style-scope ytd-comment-renderer" is-empty=""></yt-formatted-string>```
