### ISSUE TITLE
Archive project 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/yt-comment-scraper#92]
FreeTube is no longer relying on this project so we will probably do a new release then archive this project.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Mentioning dependents that havent enabled issues on their repo:
@Juninhoww2, @TimTree, @chdzma, @mauriceoegerli, @zzanehip, @chrrs, @danielfetico, @testtestingtester and @RakhithJK

Hello,

We are planning on archiving the @freetube/yt-comment-scraper module in the near future. I thought I'd reach out to the modules dependants to let them know so they can migrate to a new module if they would like.

FreeTube is switching to https://github.com/LuanRT/YouTube.js but I'm sure there are other modules that you could switch to.

**Comment by moisout** [comment]
Thank you very much for reaching out. Are you going to switch to youtube.js for the entire FreeTube project? (Meaning archival of other freetube modules)

**Comment by absidue** [comment]
Yes, we've already switched for everything else (users of those modules were pinged on the respective repos at the time that we switched), the only thing we are currently still using is yt-channel-info, as we are waiting for some changes in YouTube.js before we can migrate that over too.
See https://github.com/FreeTubeApp/FreeTube/projects/10#card-87323375

Edit: we'll still be maintaining the video.js modules

**Comment by Michal-Szczepaniak** [comment]
Correct me if this is wrong place to ask but do you know of any alternatives other than youtube.js? in this project i can get info directly from continuation and i can't do it in youtube.js
